set_property PACKAGE_PIN E3 [get_ports iclk]
set_property PACKAGE_PIN A11 [get_ports oled]

set_property IOSTANDARD LVCMOS33 [get_ports iclk]
set_property IOSTANDARD LVCMOS33 [get_ports oled]


set_property BEL F7BMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[1].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X1Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[1].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7AMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[1].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X1Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[1].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7BMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[2].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X2Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[2].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7AMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[2].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X2Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[2].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7BMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[3].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X3Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[3].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7AMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[3].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X3Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[3].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7BMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[4].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X4Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[4].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7AMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[4].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X4Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[4].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7BMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[5].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X5Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[5].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7AMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[5].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X5Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[5].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7BMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[6].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X6Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[6].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7AMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[6].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X6Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[6].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7BMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[7].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X7Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[7].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7AMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[7].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X7Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[7].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7BMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[8].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X8Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[8].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7AMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[8].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X8Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[8].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7BMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[9].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X9Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[9].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7AMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[9].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X9Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[9].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7BMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[10].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X10Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[10].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7AMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[10].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X10Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[10].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7BMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[11].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X11Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[11].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7AMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[11].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X11Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[11].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7BMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[12].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X12Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[12].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7AMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[12].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X12Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[12].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7BMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[13].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X13Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[13].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7AMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[13].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X13Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[13].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7BMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[14].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X14Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[14].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7AMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[14].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X14Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[14].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7BMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[15].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X15Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[15].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7AMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[15].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X15Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[15].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7BMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[16].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X16Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[16].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7AMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[16].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X16Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[16].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7BMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[17].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X17Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[17].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7AMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[17].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X17Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[17].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7BMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[18].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X18Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[18].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7AMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[18].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X18Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[18].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7BMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[19].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X19Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[19].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7AMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[19].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X19Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[19].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7BMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[20].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X20Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[20].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7AMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[20].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X20Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[20].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7BMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[21].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X21Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[21].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7AMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[21].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X21Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[21].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7BMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[22].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X22Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[22].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7AMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[22].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X22Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[22].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7BMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[23].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X23Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[23].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7AMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[23].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X23Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[23].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7BMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[24].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X24Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[24].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7AMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[24].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X24Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[24].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7BMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[25].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X25Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[25].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7AMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[25].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X25Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[25].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7BMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[26].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X26Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[26].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7AMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[26].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X26Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[26].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7BMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[27].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X27Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[27].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7AMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[27].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X27Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[27].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7BMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[28].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X28Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[28].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7AMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[28].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X28Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[28].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7BMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[29].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X29Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[29].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7AMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[29].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X29Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[29].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7BMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[30].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X30Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[30].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7AMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[30].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X30Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[30].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7BMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[31].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X31Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[31].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7AMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[31].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X31Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[31].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7BMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[32].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X32Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[32].inst_mux_1/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL F7AMUX [get_cells {inst_puf/inst_delay_line/inst_mux_pair[32].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property LOC SLICE_X32Y100 [get_cells {inst_puf/inst_delay_line/inst_mux_pair[32].inst_mux_2/inst_mux_as_muxf7.inst_muxf7}]
set_property BEL B5FF [get_cells inst_puf/inst_dff/dff_macro.inst_fdre]
set_property LOC SLICE_X32Y100 [get_cells inst_puf/inst_dff/dff_macro.inst_fdre]

set_property IOSTANDARD LVCMOS33 [get_ports {idimmer[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {idimmer[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {idimmer[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {idimmer[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports iforce_challenge]
set_property PACKAGE_PIN D9 [get_ports iforce_challenge]
set_property PACKAGE_PIN A8 [get_ports {idimmer[3]}]
set_property PACKAGE_PIN C11 [get_ports {idimmer[2]}]
set_property PACKAGE_PIN C10 [get_ports {idimmer[1]}]
set_property PACKAGE_PIN A10 [get_ports {idimmer[0]}]

set_property BEL B5FF [get_cells inst_fsm/pulse_reg]
set_property LOC SLICE_X0Y100 [get_cells inst_fsm/pulse_reg]

set_false_path -from [get_pins inst_fsm/pulse_reg/C] -through [get_cells -hierarchical *puf*] -to [get_pins inst_puf/inst_dff/dff_macro.inst_fdre/D]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list ist_clk_wiz/inst/oclk]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 5 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {inst_fsm/k[0]} {inst_fsm/k[1]} {inst_fsm/k[2]} {inst_fsm/k[3]} {inst_fsm/k[4]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 24 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {inst_fsm/resp24[0]} {inst_fsm/resp24[1]} {inst_fsm/resp24[2]} {inst_fsm/resp24[3]} {inst_fsm/resp24[4]} {inst_fsm/resp24[5]} {inst_fsm/resp24[6]} {inst_fsm/resp24[7]} {inst_fsm/resp24[8]} {inst_fsm/resp24[9]} {inst_fsm/resp24[10]} {inst_fsm/resp24[11]} {inst_fsm/resp24[12]} {inst_fsm/resp24[13]} {inst_fsm/resp24[14]} {inst_fsm/resp24[15]} {inst_fsm/resp24[16]} {inst_fsm/resp24[17]} {inst_fsm/resp24[18]} {inst_fsm/resp24[19]} {inst_fsm/resp24[20]} {inst_fsm/resp24[21]} {inst_fsm/resp24[22]} {inst_fsm/resp24[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 4 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {inst_fsm/state[0]} {inst_fsm/state[1]} {inst_fsm/state[2]} {inst_fsm/state[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {inst_fsm/challenge[0]} {inst_fsm/challenge[1]} {inst_fsm/challenge[2]} {inst_fsm/challenge[3]} {inst_fsm/challenge[4]} {inst_fsm/challenge[5]} {inst_fsm/challenge[6]} {inst_fsm/challenge[7]} {inst_fsm/challenge[8]} {inst_fsm/challenge[9]} {inst_fsm/challenge[10]} {inst_fsm/challenge[11]} {inst_fsm/challenge[12]} {inst_fsm/challenge[13]} {inst_fsm/challenge[14]} {inst_fsm/challenge[15]} {inst_fsm/challenge[16]} {inst_fsm/challenge[17]} {inst_fsm/challenge[18]} {inst_fsm/challenge[19]} {inst_fsm/challenge[20]} {inst_fsm/challenge[21]} {inst_fsm/challenge[22]} {inst_fsm/challenge[23]} {inst_fsm/challenge[24]} {inst_fsm/challenge[25]} {inst_fsm/challenge[26]} {inst_fsm/challenge[27]} {inst_fsm/challenge[28]} {inst_fsm/challenge[29]} {inst_fsm/challenge[30]} {inst_fsm/challenge[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 10 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {inst_fsm/resp_num[0]} {inst_fsm/resp_num[1]} {inst_fsm/resp_num[2]} {inst_fsm/resp_num[3]} {inst_fsm/resp_num[4]} {inst_fsm/resp_num[5]} {inst_fsm/resp_num[6]} {inst_fsm/resp_num[7]} {inst_fsm/resp_num[8]} {inst_fsm/resp_num[9]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list inst_fsm/bad_challenge]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list inst_fsm/pulse]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list inst_fsm/shift]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list inst_fsm/start]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
