set_property PACKAGE_PIN E3 [get_ports iclk]
set_property PACKAGE_PIN D9 [get_ports iforce_challenge]
set_property PACKAGE_PIN C11 [get_ports {idimmer[1]}]
set_property PACKAGE_PIN C10 [get_ports {idimmer[2]}]
set_property PACKAGE_PIN A8 [get_ports {idimmer[0]}]
set_property PACKAGE_PIN A10 [get_ports {idimmer[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {idimmer[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {idimmer[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {idimmer[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {idimmer[0]}]
set_property PACKAGE_PIN A11 [get_ports oled]
set_property IOSTANDARD LVCMOS33 [get_ports iclk]
set_property IOSTANDARD LVCMOS33 [get_ports iforce_challenge]
set_property IOSTANDARD LVCMOS33 [get_ports oled]

